### ISSUE TITLE
Implement Contribution Logic

### ISSUE THREAD

**Issue by jdnichollsc** [proyecto26/concertx-frontend#28]
Enable Backers to Contribute to Campaigns.

**Definition of Done:**
- [ ] Backers can pledge an amount to a campaign.
- [ ] Contributions are tracked via a Contribution account.
- [ ] Contributions are validated (e.g., within campaign deadline).

**Tasks:**
- [ ] Define the Contribution struct.
- [ ] Create an instruction for backers to contribute to a campaign.
- [ ] Validate contribution (check campaign deadline and status).
- [ ] Update campaign’s current_amount when a contribution is made.

**Code Example:**
```rs
#[account]
pub struct Contribution {
    pub campaign: Pubkey,             // Associated campaign account
    pub backer: Pubkey,               // Backer's wallet address
    pub amount: u64,                  // Amount contributed
    pub pledged_at: i64,              // Timestamp of the pledge
}

#[derive(Accounts)]
pub struct Contribute<'info> {
    #[account(mut)]
    pub campaign: Account<'info, Campaign>,
    #[account(init, payer = backer, space = 8 + Contribution::MAX_SIZE, seeds = [b"contribution", campaign.key().as_ref(), backer.key().as_ref()], bump)]
    pub contribution: Account<'info, Contribution>,
    #[account(mut)]
    pub backer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

pub fn contribute(ctx: Context<Contribute>, amount: u64) -> Result<()> {
    let campaign = &mut ctx.accounts.campaign;
    require!(Clock::get()?.unix_timestamp < campaign.end_date, ErrorCode::CampaignExpired);
    require!(campaign.status == 0, ErrorCode::InvalidCampaignStatus);

    campaign.current_amount += amount;

    let contribution = &mut ctx.accounts.contribution;
    contribution.campaign = campaign.key();
    contribution.backer = *ctx.accounts.backer.key;
    contribution.amount = amount;
    contribution.pledged_at = Clock::get()?.unix_timestamp;

    Ok(())
}
```
