### ISSUE TITLE
Claim Funds

### ISSUE THREAD

**Issue by jdnichollsc** [proyecto26/concertx-frontend#30]
Allow Campaign Creators to Claim Funds

**Definition of Done:**
- [ ] Creators can claim funds if the campaign is successfully funded.
- [ ] Only creators can withdraw funds.
- [ ] Validate that the campaign has met its funding goal.

**Tasks:**
- [ ] Add an instruction for fund withdrawal.
- [ ] Validate campaign funding and status before allowing withdrawals.
- [ ] Transfer funds to the creator’s wallet.
